version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - PERSONAL_DATA_DB_USERNAME=root
      - PERSONAL_DATA_DB_PASSWORD=root
      - PERSONAL_DATA_DB_HOST=localhost
      - PERSONAL_DATA_DB_NAME=my_db
